name: CI and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Adjust this to match your project's Python version

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install

    - name: Run linters and tests
      run: |
        poetry run pre-commit run --all-files
        poetry run pytest

  publish:
    needs: test  # This ensures the publish job runs only after the test job succeeds
    runs-on: ubuntu-latest
    if: github.event_name == 'release'  # Only run on releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust this to match your project's Python version

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry build
        poetry publish --username $TWINE_USERNAME --password $TWINE_PASSWORD
